[package]
name = "blackwall-ebpf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blackwall-ebpf"
path = "src/main.rs"

[dependencies]
common = { path = "../common", default-features = false }
aya-ebpf = "0.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
opt-level = 2
strip = "none"
debug = 2
