[package]
name = "blackwall"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blackwall"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
aya = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
papaya = { workspace = true }
crossbeam-queue = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
